### ISSUE TITLE
 TypeError: Cannot read property 'statusMessage' of undefined

### ISSUE THREAD

**Issue by aahutsal** [gutsal-arsen/raphael-elvanto#18]
```
[grunt-develop] > /home/archer/raphael-elvanto/routes/crawl.js:293
    console.log('Response status message: ' + response.statusMessage);
                                                      ^

TypeError: Cannot read property 'statusMessage' of undefined
    at Request._callback (/home/archer/raphael-elvanto/routes/crawl.js:293:55)
    at self.callback (/home/archer/raphael-elvanto/node_modules/request/request.js:200:22)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestError (/home/archer/raphael-elvanto/node_modules/request/request.js:831:8)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at TLSSocket.socketErrorListener (_http_client.js:295:9)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at emitErrorNT (net.js:1253:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
>> application exited with code 1
>> File "views/layout.jade" changed.
```

**Comment by vitalyp** [comment]
omg

**Comment by vitalyp** [comment]
fixed by https://github.com/gutsal-arsen/raphael-elvanto/commit/9e5a712eb638990ac930d5e28fce555060525864

**Comment by vitalyp** [comment]
updated https://github.com/gutsal-arsen/raphael-elvanto/commit/5e81115882ac92f144416bf856285c34fec9bcaa
